"""Hand-read transcriptions for images 71-96."""

NG = "NG"


def releve(rid, ref, mapref="", alt="", asp="", slope="", cover="", area="", sprep=""):
    return {
        "releve_id": str(rid),
        "ref_code": ref,
        "map_reference": str(mapref),
        "os_grid_square": NG,
        "altitude_ft": str(alt),
        "aspect_deg": str(asp),
        "slope_deg": str(slope),
        "cover_pct": str(cover),
        "plot_area_m2": str(area),
        "species_reported": str(sprep),
    }


def cells(text):
    return text.split()


def sp(name, text, c="", d="", needs_review=False, note=""):
    row = {"name": name, "cells": cells(text), "C": c, "D": d}
    if needs_review:
        row["needs_review"] = True
        row["note"] = note
    return row


def sparse_sp(name, n_releves, entries):
    row = ["."] * n_releves
    for releve_id, value in entries.items():
        row[releve_id - 1] = str(value)
    return {"name": name, "cells": row}


TABLE_4_53 = {
    "image": "images/Birks-HJB-1973-Present-Flora-Veg-Skye_71.png",
    "table_id_raw": "Table 4.53",
    "association": "Epiphytic bryophytes and lichens in the Betula-Vaccinium myrtillus and Corylus-Oxalis acetosella Associations",
    "n_releves": "13",
    "total_species": "60",
    "mean_species": "20.5; 25.6",
    "releves": [
        releve(1, "B68 317", "", "", "", "", "", "", 24),
        releve(2, "B67 097", "", "", "", "", "", "", 14),
        releve(3, "B67 040", "", "", "", "", "", "", 29),
        releve(4, "B67 096", "", "", "", "", "", "", 27),
        releve(5, "B67 100", "", "", "", "", "", "", 11),
        releve(6, "B67 120", "", "", "", "", "", "", 18),
        releve(7, "B67 098", "", "", "", "", "", "", 36),
        releve(8, "B67 101", "", "", "", "", "", "", 22),
        releve(9, "B67 105", "", "", "", "", "", "", 22),
        releve(10, "B67 041", "", "", "", "", "", "", 31),
        releve(11, "B67 078", "", "", "", "", "", "", 19),
        releve(12, "B68 320", "", "", "", "", "", "", 28),
        releve(13, "B68 137", "", "", "", "", "", "", 21),
    ],
    "species": [
        sp("Hymenophyllum wilsonii", "x x x x x x . . . . . . ."),
        sp("Camptothecium sericeum", ". . . . . . x . . . x . x"),
        sp("Dicranum scoparium", "x x x x x x x x . . . . ."),
        sp("Brachythecium striatum", ". . . . . . . x x x x . ."),
        sp("Hylocomium brevirostre", ". . . . . . x . x x x x ."),
        sp("Hypnum cupressiforme var. filiforme", "x x . . . . x x x x . x x"),
        sp("H. cupressiforme var. resupinatum", "x x x x x x x x x x x x x"),
        sp("Isothecium myosuroides", "x x x x x x x x x x x x x"),
        sp("I. myurum", ". . . . . . . . . x . . x"),
        sp("Mnium hornum", "x . x . . x . . x . x . ."),
        sp("Neckera complanata", ". . . . . . x x . x . x ."),
        sp("Polytrichum formosum", "x x x . . x . x . . . . ."),
        sp("Ulota bruchii", "x x x x x x x x x x x x x"),
        sp("U. crispa", "x x x x x x x x x x x x x"),
        sp("U. phyllantha", "x . x x . x x x x x x x x"),
        sp("U. vittata", ". . . . . . x x x x x x x"),
        sp("Aphanolejeunea microscopica", "x . . x . . . . . . . . ."),
        sp("Frullania dilatata", ". . x x . . x x x x x x x"),
        sp("F. germana", "x . x . . x x x x x x x x"),
        sp("F. tamarisci", "x x x x x x x x x x x x x"),
        sp("Lejeunea ulicina", "x . x x . x x x x x . x x"),
        sp("Lepidozia reptans", "x . x x x x . . . . . . ."),
        sp("Metzgeria furcata", ". . . . . . x x x x x x x"),
        sp("Mylia anomala", "x . . x . x . . . . . . ."),
        sp("Plagiochila punctata", "x x x x x x . . . . . . ."),
        sp("P. spinulosa", "x x x x x x . . . . . . ."),
        sp("P. tridenticulata", "x . . x . . . . . . . . ."),
        sp("Radula complanata", ". . . . . . x x x x x x x"),
        sp("Scapania gracilis", "x x x x x x . . . . . . ."),
        sp("Dimerella lutea", ". . . . . . x . . x x x ."),
        sp("Leptogium burgessii", ". . . . . . x . . x x x ."),
        sp("Lobaria laetevirens", "x x x x . x x . . x . x ."),
        sp("L. pulmonaria", ". x x x . . x . . x . x x"),
        sp("L. scrobiculata", ". . . . . . x . . . . x ."),
        sp("Normandina pulchella", ". . . . . . x x . . . . ."),
        sp("Pannaria pezizoides", ". . . . . . x . x x . x x"),
        sp("P. rubiginosa", ". . . . . . x x x x . x ."),
        sp("Parmeliella atlantica", ". . . . . . x x . x . x ."),
        sp("P. plumbea", ". . . . . . x x x x . x x"),
        sp("Pseudocyphellaria thouarsii", "x . x x . . x . . . . x ."),
        sp("Pyrenula nitida", ". . . . . . x . . x . . ."),
        sp("Sphaerophorus globosus", ". . x x . x . . . . . . ."),
        sp("Sticta fuliginosa", "x . x x . . x x x x x x x"),
        sp("S. limbata", ". . . . . . x . x x . x ."),
        sp("S. sylvatica", "x . x x . . x . x x x x x"),
        sparse_sp("Adelanthus decipiens", 13, {3: "x"}),
        sparse_sp("Menegazzia terebrata", 13, {3: "x"}),
        sparse_sp("Parmelia crinita", 13, {3: "x"}),
        sparse_sp("P. laevigata", 13, {3: "x"}),
        sparse_sp("P. saxatilis", 13, {3: "x"}),
        sparse_sp("Usnea rubiginea", 13, {3: "x"}),
        sparse_sp("Douinia ovata", 13, {4: "x"}),
        sparse_sp("Cetraria glauca", 13, {4: "x"}),
        sparse_sp("Pseudocyphellaria crocata", 13, {4: "x"}),
        sparse_sp("Usnea fragilescens", 13, {4: "x"}),
        sparse_sp("Zygodon conoideus", 13, {7: "x"}),
        sparse_sp("Graphis scripta", 13, {7: "x"}),
        sparse_sp("Nephroma laevigatum", 13, {7: "x"}),
        sparse_sp("Thelotrema lepadinum", 13, {7: "x"}),
        sparse_sp("Lecanora allophana", 13, {10: "x"}),
        sparse_sp("Parmeliella corallinoides", 13, {10: "x"}),
        sparse_sp("Metzgeria fruticulosa", 13, {13: "x"}),
    ],
}


TABLE_4_54A = {
    "image": "images/Birks-HJB-1973-Present-Flora-Veg-Skye_72.png",
    "table_id_raw": "Table 4.54",
    "association": "Bryophytes of decaying logs in the Betula-Vaccinium myrtillus Association",
    "n_releves": "6",
    "total_species": "22",
    "mean_species": "14.2",
    "releves": [
        releve(1, "B68 317", "", "", "", "", "", "", 21),
        releve(2, "B67 097", "", "", "", "", "", "", 7),
        releve(3, "B67 040", "", "", "", "", "", "", 16),
        releve(4, "B67 096", "", "", "", "", "", "", 10),
        releve(5, "B67 100", "", "", "", "", "", "", 11),
        releve(6, "B67 120", "", "", "", "", "", "", 20),
    ],
    "species": [
        sp("Dicranodontium denudatum", "x . x . . x"),
        sp("Dicranum scoparium", "x x x x x x"),
        sp("Hypnum cupressiforme", "x x x x x x"),
        sp("Isothecium myosuroides", "x x x x x x"),
        sp("Tetraphis pellucida", "x . x x . x"),
        sp("Blepharostoma trichophyllum", "x . . . . x"),
        sp("Cephalozia bicuspidata", "x x x x x x"),
        sp("C. connivens", "x . x . . x"),
        sp("C. media", "x . . . . x"),
        sp("Lepidozia pinnata", "x . x . . ."),
        sp("L. reptans", "x x x x x x"),
        sp("Lophocolea heterophylla", "x . . . . x"),
        sp("Lophozia incisa", "x . x x . x"),
        sp("L. ventricosa", "x x x x x x"),
        sp("Nowellia curvifolia", "x . x . x x"),
        sp("Plagiochila spinulosa", "x . x . x x"),
        sp("Riccardia latifrons", ". . . . x x"),
        sp("R. palmata", "x . . x x x"),
        sp("Scapania gracilis", "x x x x x x"),
        sp("S. umbrosa", "x . x . . x"),
        sp("Tritomaria exsecta", "x . . . . x"),
        sp("T. exsectiformis", "x . x . . ."),
    ],
}


TABLE_4_54B = {
    "image": "images/Birks-HJB-1973-Present-Flora-Veg-Skye_72.png",
    "table_id_raw": "Table 4.54",
    "association": "Bryophytes of decaying logs in the Corylus-Oxalis acetosella Association",
    "n_releves": "6",
    "total_species": "22",
    "mean_species": "12.7",
    "releves": [
        releve(7, "B67 098", "", "", "", "", "", "", 18),
        releve(8, "B67 101", "", "", "", "", "", "", 8),
        releve(9, "B67 105", "", "", "", "", "", "", 15),
        releve(10, "B67 041", "", "", "", "", "", "", 11),
        releve(11, "B67 078", "", "", "", "", "", "", 11),
        releve(12, "B68 320", "", "", "", "", "", "", 13),
    ],
    "species": [
        sp("Dicranodontium denudatum", "x . x . x ."),
        sp("Dicranum scoparium", "x x x x x x"),
        sp("Hypnum cupressiforme", "x x x x x x"),
        sp("Isothecium myosuroides", "x x x x x x"),
        sp("Tetraphis pellucida", "x . x x . ."),
        sp("Blepharostoma trichophyllum", "x . . . x x"),
        sp("Cephalozia bicuspidata", "x x x x x x"),
        sp("C. connivens", "x . . . . ."),
        sp("C. media", "x . . . . ."),
        sp("Lepidozia pinnata", ". . . . . ."),
        sp("L. reptans", "x x x x x x"),
        sp("Lophocolea heterophylla", ". . . . . ."),
        sp("Lophozia incisa", "x . x x x x"),
        sp("L. ventricosa", "x x x x . x"),
        sp("Nowellia curvifolia", "x x x . . x"),
        sp("Plagiochila spinulosa", "x . x x x x"),
        sp("Riccardia latifrons", ". x x . . ."),
        sp("R. palmata", "x . x . . x"),
        sp("Scapania gracilis", "x . x x x x"),
        sp("S. umbrosa", "x . x x x x"),
        sp("Tritomaria exsecta", "x . . . . ."),
        sp("T. exsectiformis", ". . . . . ."),
    ],
}


TABLE_4_55 = {
    "image": "images/Birks-HJB-1973-Present-Flora-Veg-Skye_73.png",
    "table_id_raw": "Table 4.55",
    "class": "QUERCO-FAGETEA",
    "order": "FAGETALIA SYLVATICAE",
    "alliance": "Fagion sylvaticae",
    "association": "Fraxinus excelsior-Brachypodium sylvaticum",
    "n_releves": "5",
    "total_species": "95",
    "mean_species": "42.4",
    "releves": [
        releve(1, "B68-095", "393643", 100, 315, 5, 100, 16, 40),
        releve(2, "B67-099", "613118", 300, 315, 10, 100, 16, 44),
        releve(3, "B67-002", "609211", 100, 0, 5, 100, 16, 40),
        releve(4, "B67-103", "607202", 100, 0, 3, 100, 16, 44),
        releve(5, "B68-330", "575200", 100, 315, 5, 100, 4, 44),
    ],
    "species": [
        sp("Betula pubescens ssp. odorata", ". 3 4 + .", "III", "1.6"),
        sp("Corylus avellana", "4 8 8 9 8", "V", "7.4"),
        sp("Fraxinus excelsior", "6 4 5 3 6", "V", "4.8"),
        sp("Sorbus aucuparia", "3 3 3 . .", "III", "1.8"),
        sp("Ulmus glabra", "7 + . . .", "II", "1.6"),
        sp("Viburnum opulus", ". . 3 2 .", "II", "1.0"),
        sp("Athyrium filix-femina", "5 . 2 . .", "II", "1.4"),
        sp("Blechnum spicant", ". 2 2 . .", "II", "0.8"),
        sp("Dryopteris filix-mas", "5 2 3 2 .", "IV", "2.4"),
        sp("Pteridium aquilinum", ". 1 . . 3", "II", "0.8"),
        sp("Agrostis tenuis", "3 3 3 3 2", "V", "2.8"),
        sp("Anthoxanthum odoratum", "3 3 3 . 4", "IV", "2.6"),
        sp("Arrhenatherum elatius", "3 . 1 . 3", "II", "1.4"),
        sp("Brachypodium sylvaticum", "6 7 7 6 7", "V", "6.6"),
        sp("Dactylis glomerata", "3 2 2 3 3", "V", "2.6"),
        sp("Deschampsia cespitosa", ". . . 3 2", "II", "1.0"),
        sp("Allium ursinum", "3 3 . . 3", "III", "1.8"),
        sp("Carex sylvatica", ". 1 . 3 .", "II", "0.8"),
        sp("Endymion non-scriptus", ". 4 3 4 .", "III", "2.2"),
        sp("Anemone nemorosa", ". 2 . 1 .", "II", "0.6"),
        sp("Bellis perennis", ". 3 . 1 .", "II", "0.8"),
        sp("Cardamine flexuosa", "+ + . . 1", "III", "0.6"),
        sp("Circaea intermedia", ". 3 3 . .", "II", "1.2"),
        sp("C. lutetiana", "1 . . . 3", "II", "0.8"),
        sp("Conopodium majus", "1 2 2 3 .", "IV", "1.6"),
        sp("Epilobium montanum", "2 . . . 2", "II", "0.8"),
        sp("Filipendula ulmaria", "7 3 3 3 6", "V", "4.4"),
        sp("Fragaria vesca", "2 1 2 . 3", "IV", "1.6"),
        sp("Galium saxatile", ". . 2 2 .", "II", "0.8"),
        sp("Geranium robertianum", "3 . 1 2 2", "IV", "1.6"),
        sp("Geum rivale", ". 3 3 4 .", "IV", "2.0"),
        sp("Heracleum sphondylium", "4 . . . 5", "II", "1.8"),
        sp("Lysimachia nemorum", "4 1 4 2 .", "IV", "2.2"),
        sp("Oxalis acetosella", "2 4 4 5 3", "V", "3.6"),
        sp("Potentilla erecta", ". 2 . 1 .", "II", "0.6"),
        sp("Primula vulgaris", "3 4 4 5 5", "V", "4.2"),
        sp("Prunella vulgaris", "+ . 1 . 2", "II", "0.8"),
        sp("Ranunculus acris", "2 1 . . .", "II", "0.6"),
        sp("Sanicula europaea", "+ 2 3 . .", "III", "1.2"),
        sp("Vicia sepium", ". . . 1 2", "II", "0.6"),
        sp("Viola riviniana", "2 2 3 2 3", "V", "2.4"),
        sp("Ctenidium molluscum", ". 1 5 1 5", "IV", "2.4"),
        sp("Eurhynchium praelongum", "1 3 . . 1", "III", "1.0"),
        sp("E. striatum", ". 2 . 4 3", "III", "1.8"),
        sp("Fissidens taxifolius", ". + . 1 .", "II", "0.4"),
        sp("Hylocomium brevirostre", "+ 2 . 4 5", "IV", "2.4"),
        sp("H. splendens", ". 3 3 1 .", "III", "1.4"),
        sp("Isothecium myosuroides", ". . 2 1 .", "II", "0.6"),
        sp("I. myurum", "4 . 3 . 1", "III", "1.6"),
        sp("Mnium undulatum", "2 . . 2 1", "III", "1.0"),
        sp("Rhytidiadelphus triquetrus", "6 2 2 3 .", "IV", "2.6"),
        sp("Thuidium delicatulum", ". 3 . 4 .", "II", "1.4"),
        sp("T. tamariscinum", "2 3 2 1 2", "V", "2.0"),
        sp("*Plagiochila asplenioides", ". . . 1 2", "II", "0.6"),
        sparse_sp("Angelica sylvestris", 5, {1: "4"}),
        sparse_sp("Chrysosplenium oppositifolium", 5, {1: "5"}),
        sparse_sp("Digitalis purpurea", 5, {1: "2"}),
        sparse_sp("Galium aparine", 5, {1: "1"}),
        sparse_sp("Silene dioica", 5, {1: "3"}),
        sparse_sp("Tussilago farfara", 5, {1: "+"}),
        sparse_sp("Urtica dioica", 5, {1: "3"}),
        sparse_sp("Prunus padus", 5, {2: "3"}),
        sparse_sp("Helictotrichon pratense", 5, {2: "1"}),
        sparse_sp("Glechoma hederacea", 5, {2: "2"}),
        sparse_sp("Rhytidiadelphus loreus", 5, {2: "2"}),
        sparse_sp("Lophocolea bidentata", 5, {2: "1"}),
        sparse_sp("Lonicera periclymenum", 5, {3: "+"}),
        sparse_sp("Gymnadenia conopsea", 5, {3: "1"}),
        sparse_sp("Listera ovata", 5, {3: "2"}),
        sparse_sp("Lathyrus montanus", 5, {3: "1"}),
        sparse_sp("Melampyrum pratense", 5, {3: "1"}),
        sparse_sp("Breutelia chrysocoma", 5, {3: "4"}),
        sparse_sp("Polytrichum formosum", 5, {3: "3"}),
        sparse_sp("Thelypteris phegopteris", 5, {4: "1"}),
        sparse_sp("Ajuga reptans", 5, {4: "2"}),
        sparse_sp("Veronica chamaedrys", 5, {4: "3"}),
        sparse_sp("Atrichum undulatum", 5, {4: "1"}),
        sparse_sp("Fissidens cristatus", 5, {4: "1"}),
        sparse_sp("Pseudoscleropodium purum", 5, {4: "2"}),
        sparse_sp("Lejeunea cavifolia", 5, {4: "1"}),
        sparse_sp("Pellia epiphylla", 5, {4: "1"}),
        sparse_sp("Scapania aspera", 5, {4: "1"}),
        sparse_sp("Rubus fruticosus agg.", 5, {5: "1"}),
        sparse_sp("Asplenium trichomanes", 5, {5: "1"}),
        sparse_sp("Senecio jacobaea", 5, {5: "2"}),
        sparse_sp("Succisa pratensis", 5, {5: "2"}),
        sparse_sp("Anomodon viticulosus", 5, {5: "3"}),
        sparse_sp("Bryum capillare", 5, {5: "1"}),
        sparse_sp("Camptothecium sericeum", 5, {5: "3"}),
        sparse_sp("Rhytidiadelphus squarrosus", 5, {5: "2"}),
        sparse_sp("Thamnium alopecurum", 5, {5: "2"}),
        sparse_sp("Tortella tortuosa", 5, {5: "2"}),
        sparse_sp("Marchesinia mackaii", 5, {5: "2"}),
        sparse_sp("Metzgeria pubescens", 5, {5: "1"}),
        sparse_sp("Peltigera canina", 5, {5: "1"}),
    ],
}


TABLE_4_56 = {
    "image": "images/Birks-HJB-1973-Present-Flora-Veg-Skye_74.png",
    "table_id_raw": "Table 4.56",
    "association": "Limestone pavement communities",
    "n_releves": "5",
    "total_species": "129",
    "mean_species": "72.8",
    "releves": [
        releve(1, "B68-263", "5818", 100, 270, 5, "", 50, 69),
        releve(2, "B68-302", "6112", 300, 270, 5, "", 30, 52),
        releve(3, "B68-329", "5720", 100, 225, 5, "", 200, 85),
        releve(4, "B68-303", "6119", 500, 315, 10, "", 200, 95),
        releve(5, "B68-304", "6119", 500, 315, 10, "", 50, 63),
    ],
    "species": [
        sp("Asplenium adiantum-nigrum", ". x . x ."),
        sp("A. ruta-muraria", "x . x x ."),
        sp("A. trichomanes", "x x x x x"),
        sp("A. viride", ". x . x x"),
        sp("Camptothecium sericeum", "x . x x x"),
        sp("Encalypta streptocarpa", ". x x x ."),
        sp("Fissidens cristatus", "x x x x x"),
        sp("Grimmia apocarpa", "x x x x x"),
        sp("Neckera crispa", "x x x x x"),
        sp("Orthotrichum anomalum", ". x x x ."),
        sp("Tortella tortuosa", "x x x . x"),
        sp("Trichostomum crispulum", "x . . x ."),
        sp("Collema crispum", "x x x x x"),
        sp("Dryas octopetala", "x . . x x"),
        sp("Rosa pimpinellifolia", "x . x x ."),
        sp("Anthoxanthum odoratum", "x x x x ."),
        sp("Arrhenatherum elatius", "x . x x x"),
        sp("Festuca ovina", "x . . x x"),
        sp("F. rubra", "x . x x x"),
        sp("F. vivipara", "x x x x x"),
        sp("Molinia caerulea", "x x x x x"),
        sp("Sieglingia decumbens", "x x . x ."),
        sp("Carex flacca", "x x x x x"),
        sp("C. pulicaris", "x x x x x"),
        sp("Antennaria dioica", "x . x x x"),
        sp("Bellis perennis", "x x x x ."),
        sp("Cirsium vulgare", "x . x x ."),
        sp("Euphrasia confusa and E. nemorosa", "x x x x ."),
        sp("Galium verum", "x . x . ."),
        sp("Hieracium pilosella", "x x x x x"),
        sp("Hypericum pulchrum", "x . x x x"),
        sp("Linum catharticum", "x x x x x"),
        sp("Lotus corniculatus", "x . x x x"),
        sp("Plantago lanceolata", "x x x x ."),
        sp("P. maritima", "x x x x x"),
        sp("Polygala vulgaris", ". x x . ."),
        sp("Polygonum viviparum", "x . . x x"),
        sp("Potentilla erecta", "x . x x x"),
        sp("Prunella vulgaris", "x . x x ."),
        sp("Ranunculus repens", "x . . x ."),
        sp("Succisa pratensis", ". x x x x"),
        sp("Thymus drucei", "x x x x x"),
        sp("Viola riviniana", "x x x x x"),
        sp("Campylium protensum", "x . x . ."),
        sp("Ditrichum flexicaule", ". x x x x"),
        sp("Hylocomium splendens", "x x . x x"),
        sp("*Hypnum cupressiforme", ". x x x x"),
        sp("Crataegus monogyna", "x . x x ."),
        sp("Corylus avellana", ". . x x x"),
        sp("Hedera helix", "x x x x x"),
        sp("Salix aurita", "x x . x ."),
        sp("Athyrium filix-femina", "x . . x ."),
        sp("Dryopteris borreri", "x x . x x"),
        sp("Phyllitis scolopendrium", "x x x x x"),
        sp("Polystichum aculeatum", "x x x x x"),
        sp("Pteridium aquilinum", ". . x x x"),
        sp("Brachypodium sylvaticum", "x x x x x"),
        sp("Allium ursinum", "x . x x x"),
        sp("Endymion non-scriptus", ". . x x x"),
        sp("Listera ovata", ". . x x ."),
        sp("Anemone nemorosa", "x . . x x"),
        sp("Epilobium montanum", ". . x x ."),
        sp("Filipendula ulmaria", "x . x x ."),
        sp("Hypericum androsaemum", "x . x . ."),
        sp("Oxalis acetosella", ". . x x x"),
        sp("Primula vulgaris", "x x x x x"),
        sp("Sanicula europaea", "x . x x x"),
        sp("Urtica dioica", "x . . x ."),
        sp("Valeriana officinalis", "x . x x x"),
        sp("Vicia sepium", "x x x x ."),
        sp("Hylocomium brevirostre", "x x x x ."),
        sp("Isothecium myosuroides", ". x . x x"),
        sp("Mnium undulatum", ". x x x x"),
        sp("Thamnium alopecurum", ". . x x x"),
        sp("Thuidium tamariscinum", ". . x x ."),
        sp("Plagiochila asplenioides", "x . x x x"),
        sp("Calluna vulgaris", "x x . x ."),
        sp("Rubus saxatilis", "x x x x x"),
        sp("Epipactis atrorubens", ". . x x ."),
        sp("Fragaria vesca", ". . x x ."),
        sp("Geranium robertianum", "x x x x x"),
        sp("Leontodon autumnalis", "x x x . ."),
        sp("Pinguicula vulgaris", "x . . x ."),
        sp("Solidago virgaurea", ". x x . ."),
        sp("Teucrium scorodonia", "x x x x x"),
        sp("Ctenidium molluscum", "x x x x x"),
        sp("Hypnum cupressiforme", "x . . x x"),
        sp("†Rhacomitrium lanuginosum", "x . . x x"),
        sp("Conocephalum conicum", "x x . x ."),
        sp("Metzgeria pubescens", ". . x x ."),
        sp("Scapania aspera", "x x x x x"),
        sparse_sp("Erica cinerea", 5, {2: "x"}),
        sparse_sp("Agrostis canina", 5, {2: "x"}),
        sparse_sp("Centaurea nigra", 5, {2: "x"}),
        sparse_sp("Tortula muralis", 5, {2: "x"}),
        sparse_sp("Frullania tamarisci", 5, {2: "x"}),
        sparse_sp("Fraxinus excelsior", 5, {3: "x"}),
        sparse_sp("Salix repens", 5, {3: "x"}),
        sparse_sp("Festuca gigantea", 5, {3: "x"}),
        sparse_sp("Angelica sylvestris", 5, {3: "x"}),
        sparse_sp("Anthyllis vulneraria", 5, {3: "x"}),
        sparse_sp("Arabis hirsuta", 5, {3: "x"}),
        sparse_sp("Senecio jacobaea", 5, {3: "x"}),
        sparse_sp("Anomodon viticulosus", 5, {3: "x"}),
        sparse_sp("Mnium longirostrum", 5, {3: "x"}),
        sparse_sp("Neckera complanata", 5, {3: "x"}),
        sparse_sp("Orthotrichum rupestre", 5, {3: "x"}),
        sparse_sp("Marchesinia mackaii", 5, {3: "x"}),
        sparse_sp("Porella laevigata", 5, {3: "x"}),
        sparse_sp("Protoblastenia rupestris", 5, {3: "x"}),
        sparse_sp("Lonicera periclymenum", 5, {4: "x"}),
        sparse_sp("Sorbus aucuparia", 5, {4: "x"}),
        sparse_sp("Cystopteris fragilis", 5, {4: "x"}),
        sparse_sp("Cardamine pratensis", 5, {4: "x"}),
        sparse_sp("Cirsium heterophyllum", 5, {4: "x"}),
        sparse_sp("Geum rivale", 5, {4: "x"}),
        sparse_sp("Heracleum sphondylium", 5, {4: "x"}),
        sparse_sp("Stachys sylvatica", 5, {4: "x"}),
        sparse_sp("Acrocladium cuspidatum", 5, {4: "x"}),
        sparse_sp("Bryum capillare", 5, {4: "x"}),
        sparse_sp("Rhytidiadelphus triquetrus", 5, {4: "x"}),
        sparse_sp("Arctostaphylos uva-ursi", 5, {5: "x"}),
        sparse_sp("Polypodium vulgare", 5, {5: "x"}),
        sparse_sp("Polystichum lonchitis", 5, {5: "x"}),
        sparse_sp("Myosotis discolor", 5, {5: "x"}),
        sparse_sp("Paris quadrifolia", 5, {5: "x"}),
        sparse_sp("Pseudoscleropodium purum", 5, {5: "x"}),
        sparse_sp("Gyalecta jenensis", 5, {5: "x"}),
        sparse_sp("Solorina saccata", 5, {5: "x"}),
    ],
}


TABLES_71_96 = [
    TABLE_4_53,
    TABLE_4_54A,
    TABLE_4_54B,
    TABLE_4_55,
    TABLE_4_56,
]
